version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: false # Set to false for production
      APP_KEY: base64:YOUR_APP_KEY # Replace with your actual key
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db
    volumes:
      - .:/var/www/html # Use volume only if necessary for development

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  adminer: # Use Adminer instead of phpMyAdmin
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: pma
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes:
  dbdata:
